apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: default
  annotations:
    kubernetes.io/elb.class: union
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
